
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.JavaGenericsIntro;

public class App {
    public static void main(String[] args) {
        System.out.println("My Generic List: ");

        GenericList<Integer> list = new GenericList<>();
        for (int i=0; i<501; i++) list.addItem(i);

        System.out.println(list.toString());

    }
}